{% set name = "mygeopackage" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2f15cbf1cc23317be5f318918c9feb8c1d2b238d91277b804cd9f4d01d1fb2df


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - folium
    - ipyfilechooser
    - ipyleaflet
    - numpy
    - pyshp
    - python >=3.6
    - scikit-learn
    - whitebox

test:
  imports:
    - mygeopackage

about:
  home: "https://github.com/yungming0119/mygeopackage"
  license: MIT
  license_family: MIT
  license_file:  LICENSE
  summary: "Python package for gis application"
  doc_url: https://yungming0119.github.io/mygeopackage/
  dev_url: https://github.com/yungming0119/mygeopackage

extra:
  recipe-maintainers:
    - yungming0119
