{% set name = "mygeopackage" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7e80b84996c7cd7e5ee623b1bdb1061a76063e74975a5c369d743769c9b0e38a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - folium
    - ipyleaflet
    - numpy
    - pyshp
    - python >=3.6
    - scikit-learn

test:
  imports:
    - mygeopackage

about:
  home: "https://github.com/yungming0119/mygeopackage"
  license: MIT
  license_family: MIT
  license_file:  LICENSE
  summary: "Python package for gis application"
  doc_url: https://yungming0119.github.io/mygeopackage/
  dev_url: https://github.com/yungming0119/mygeopackage

extra:
  recipe-maintainers:
    - yungming0119
